$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: lightgbm-deployment
endpoint_name: my-endpoint
model:
  name: mir-sample-lightgbm-ncd-model
  version: 3
  path: lightgbm-iris/model
  type: mlflow_model
instance_type: Standard_DS3_v2
instance_count: 1