$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: sklearn-deployment-script
endpoint_name: my-endpoint
model:
  name: mir-sample-sklearn-mlflow-model
  version: 1
  path: sklearn-diabetes/model
  type: mlflow_model
environment:
  image: mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference
  conda_file: sklearn-diabetes/environment/conda.yaml
code_configuration:
    code: sklearn-diabetes/src
    scoring_script: score.py
instance_type: Standard_DS3_v2
instance_count: 1