$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: AML-RAI-Environment
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest.v1
conda_file: conda_envs/python-aml-rai.yaml
