$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: openapi
endpoint_name: <my-endpoint-name>
model:
  path: ../../model-1/model
code_configuration:
  code: <CODE_DIR>
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference
  conda_file: env.yml
instance_type: Standard_DS3_v2
instance_count: 1