blank_issues_enabled: false
contact_links:
  - name: Python SDK issues
    url: https://github.com/azure/azure-sdk-for-python/issues/new
    about: Please open issues with the Azure ML Python SDK here.
  - name: CLI issues
    url: https://github.com/azure/azure-cli-extensions/issues/new
    about: Please open issues with the Azure ML CLI extension here.
