$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline_customize_output_folder
# Serverless compute is used to run this pipeline job. 
# Through serverless compute, Azure Machine Learning takes care of creating, scaling, deleting, patching and managing compute, along with providing managed network isolation, reducing the burden on you.
settings:
    default_compute: azureml:serverless
jobs:
  hello_world:
    command: echo "hello" && echo "world" > ${{outputs.output}}/hello_world-folder.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    outputs:
      output:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/${{name}}/
