name: green
endpoint_name: my-endpoint
model:
  local_path: ../../model-2/model/sklearn_regression_model.pkl
code_configuration:
  code: 
    local_path: ../../model-2/onlinescoring/
  scoring_script: score.py
environment:
  conda_file: file:../../model-2/environment/conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_F2s_v2
instance_count: 1
