name: blue3
type: kubernetes
endpoint_name: my-endpoint-local
model:
  path: ../model-1/model/
code_configuration:
  code: ../model-1/onlinescoring/
  scoring_script: score.py
environment: 
  conda_file: ../model-1/environment/conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
request_settings:
  request_timeout_ms: 3000
  max_concurrent_requests_per_instance: 1
  max_queue_wait_ms: 3000
instance_type: defaltinstancetype
resources:
  requests:
    cpu: "0.1"
    memory: "0.1Gi"
  limits:
    cpu: "0.2"
    memory: "200Mi"
liveness_probe:
  initial_delay: 10
  period: 10
  timeout: 10
  success_threshold: 1
  failure_threshold: 30
readiness_probe:
  initial_delay: 10
  period: 10
  timeout: 10
  success_threshold: 1
  failure_threshold: 30
tags:
  tag1: deployment-tag1-value
instance_count: 1
scale_settings:
  type: default
