name: azureml_py36
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - absl-py==0.11.0
    - adal==1.2.5
    - aiohttp==3.7.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - alembic==1.4.1
    - ansiwrap==0.8.4
    - antlr4-python3-runtime==4.7.2
    - applicationinsights==0.11.9
    - argcomplete==1.12.2
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astroid==2.4.2
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==20.3.0
    - autopep8==1.5.4
    - azure-appconfiguration==1.1.1
    - azure-batch==10.0.0
    - azure-cli==2.17.1
    - azure-cli-core==2.17.1
    - azure-cli-telemetry==1.0.6
    - azure-common==1.1.26
    - azure-core==1.9.0
    - azure-cosmos==3.2.0
    - azure-datalake-store==0.0.51
    - azure-functions-devops-build==0.0.22
    - azure-graphrbac==0.61.1
    - azure-identity==1.4.1
    - azure-keyvault==1.1.0
    - azure-keyvault-administration==4.0.0b2
    - azure-loganalytics==0.1.0
    - azure-mgmt-advisor==2.0.1
    - azure-mgmt-apimanagement==0.2.0
    - azure-mgmt-appconfiguration==0.6.0
    - azure-mgmt-applicationinsights==0.1.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-batch==9.0.0
    - azure-mgmt-batchai==2.0.0
    - azure-mgmt-billing==1.0.0
    - azure-mgmt-botservice==0.2.0
    - azure-mgmt-cdn==5.2.0
    - azure-mgmt-cognitiveservices==6.3.0
    - azure-mgmt-compute==18.0.0
    - azure-mgmt-consumption==2.0.0
    - azure-mgmt-containerinstance==1.5.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-containerservice==9.4.0
    - azure-mgmt-core==1.2.1
    - azure-mgmt-cosmosdb==1.0.0
    - azure-mgmt-databoxedge==0.2.0
    - azure-mgmt-datalake-analytics==0.2.1
    - azure-mgmt-datalake-nspkg==3.0.1
    - azure-mgmt-datalake-store==0.5.0
    - azure-mgmt-datamigration==0.1.0
    - azure-mgmt-deploymentmanager==0.2.0
    - azure-mgmt-devtestlabs==4.0.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-eventgrid==3.0.0rc7
    - azure-mgmt-eventhub==4.1.0
    - azure-mgmt-hdinsight==2.0.0
    - azure-mgmt-imagebuilder==0.4.0
    - azure-mgmt-iotcentral==3.0.0
    - azure-mgmt-iothub==0.12.0
    - azure-mgmt-iothubprovisioningservices==0.2.0
    - azure-mgmt-keyvault==2.2.0
    - azure-mgmt-kusto==0.3.0
    - azure-mgmt-loganalytics==0.7.0
    - azure-mgmt-managedservices==1.0.0
    - azure-mgmt-managementgroups==0.2.0
    - azure-mgmt-maps==0.1.0
    - azure-mgmt-marketplaceordering==0.2.1
    - azure-mgmt-media==2.2.0
    - azure-mgmt-monitor==0.11.0
    - azure-mgmt-msi==0.2.0
    - azure-mgmt-netapp==0.14.0
    - azure-mgmt-network==17.0.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-policyinsights==0.5.0
    - azure-mgmt-privatedns==0.1.0
    - azure-mgmt-rdbms==3.1.0rc1
    - azure-mgmt-recoveryservices==0.4.0
    - azure-mgmt-recoveryservicesbackup==0.6.0
    - azure-mgmt-redhatopenshift==0.1.0
    - azure-mgmt-redis==7.0.0rc2
    - azure-mgmt-relay==0.1.0
    - azure-mgmt-reservations==0.6.0
    - azure-mgmt-resource==12.0.0
    - azure-mgmt-search==2.1.0
    - azure-mgmt-security==0.6.0
    - azure-mgmt-servicebus==0.6.0
    - azure-mgmt-servicefabric==0.5.0
    - azure-mgmt-signalr==0.4.0
    - azure-mgmt-sql==0.21.0
    - azure-mgmt-sqlvirtualmachine==0.5.0
    - azure-mgmt-storage==11.2.0
    - azure-mgmt-synapse==0.5.0
    - azure-mgmt-trafficmanager==0.51.0
    - azure-mgmt-web==0.48.0
    - azure-multiapi-storage==0.5.2
    - azure-nspkg==3.0.2
    - azure-storage-blob==12.6.0
    - azure-storage-common==1.4.2
    - azure-storage-queue==12.1.4
    - azure-synapse-accesscontrol==0.2.0
    - azure-synapse-artifacts==0.3.0
    - azure-synapse-spark==0.2.0
    - azureml-accel-models==1.20.0
    - azureml-automl-core==1.20.0
    - azureml-automl-runtime==1.20.0
    - azureml-cli-common==1.20.0
    - azureml-contrib-dataset==1.20.0
    - azureml-contrib-fairness==1.20.0
    - azureml-contrib-gbdt==1.20.0
    - azureml-contrib-interpret==1.20.0
    - azureml-contrib-notebook==1.20.0
    - azureml-contrib-pipeline-steps==1.20.0
    - azureml-contrib-reinforcementlearning==1.20.0
    - azureml-contrib-server==1.20.0
    - azureml-contrib-services==1.20.0
    - azureml-core==1.20.0
    - azureml-datadrift==1.20.0
    - azureml-dataprep==2.7.3
    - azureml-dataprep-native==27.0.0
    - azureml-dataprep-rslex==1.5.0
    - azureml-dataset-runtime==1.20.0
    - azureml-defaults==1.20.0
    - azureml-explain-model==1.20.0
    - azureml-interpret==1.20.0
    - azureml-mlflow==1.20.0.post1
    - azureml-model-management-sdk==1.0.1b6.post1
    - azureml-opendatasets==1.20.0
    - azureml-pipeline==1.20.0
    - azureml-pipeline-core==1.20.0
    - azureml-pipeline-steps==1.20.0
    - azureml-samples==0+unknown
    - azureml-sdk==1.20.0
    - azureml-telemetry==1.20.0
    - azureml-tensorboard==1.20.0
    - azureml-train==1.20.0
    - azureml-train-automl==1.20.0
    - azureml-train-automl-client==1.20.0
    - azureml-train-automl-runtime==1.20.0
    - azureml-train-core==1.20.0
    - azureml-train-restclients-hyperdrive==1.20.0
    - azureml-widgets==1.20.0
    - backcall==0.2.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.0
    - beautifulsoup4==4.9.3
    - bleach==3.2.1
    - blessings==1.7
    - blis==0.2.4
    - bokeh==2.2.3
    - boto==2.49.0
    - boto3==1.15.18
    - botocore==1.18.18
    - bottleneck==1.3.2
    - cached-property==1.5.2
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - colorful==0.5.4
    - configparser==3.7.4
    - contextlib2==0.6.0.post1
    - contextvars==2.4
    - coremltools==2.1.0
    - cryptography==3.3.1
    - cymem==2.0.5
    - databricks-cli==0.14.1
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.3
    - distro==1.5.0
    - dm-tree==0.1.5
    - docker==4.4.1
    - dotnetcore2==2.1.20
    - en-core-web-sm==2.1.0
    - encrypted-inference==0.9
    - entrypoints==0.3
    - enum34==1.1.10
    - fabric==2.5.0
    - fairlearn==0.4.6
    - fastai==1.0.61
    - fastprogress==1.0.0
    - filelock==3.0.12
    - fire==0.3.1
    - flake8==3.8.4
    - flask==1.0.3
    - flask-cors==3.0.10
    - flatbuffers==1.12
    - fusepy==3.0.1
    - future==0.18.2
    - gast==0.3.3
    - gensim==3.8.3
    - gevent==20.12.1
    - gitdb==4.0.5
    - gitpython==3.1.12
    - google-api-core==1.24.1
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - greenlet==0.4.17
    - grpcio==1.34.0
    - gunicorn==19.9.0
    - gym==0.18.0
    - h5py==2.10.0
    - hiredis==1.1.0
    - horovod==0.19.1
    - humanfriendly==8.2
    - idna==2.10
    - idna-ssl==1.1.0
    - imageio==2.9.0
    - immutables==0.14
    - importlib-metadata==3.3.0
    - interpret-community==0.15.4
    - interpret-core==0.2.1
    - invoke==1.5.0
    - ipykernel==5.4.3
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isodate==0.6.0
    - isort==5.7.0
    - itsdangerous==1.1.0
    - javaproperties==0.5.1
    - jedi==0.18.0
    - jeepney==0.6.0
    - jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==0.14.1
    - jsmin==2.2.2
    - json-logging-py==0.2
    - json5==0.9.5
    - jsondiff==1.2.0
    - jsonpickle==1.4.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyter-server-proxy==1.5.3
    - jupyterlab==2.1.4
    - jupyterlab-nvdashboard==0.4.0
    - jupyterlab-server==1.2.0
    - jupyterlab-widgets==1.0.0
    - jupytext==1.6.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keras2onnx==1.6.0
    - kiwisolver==1.3.1
    - knack==0.7.2
    - lazy-object-proxy==1.4.3
    - liac-arff==2.5.0
    - lightgbm==2.3.0
    - lz4==3.1.1
    - mako==1.1.3
    - markdown==3.3.3
    - markdown-it-py==0.5.8
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - mlflow==1.13.1
    - mock==4.0.3
    - msal==1.8.0
    - msal-extensions==0.2.2
    - msgpack==1.0.2
    - msrest==0.6.19
    - msrestazure==0.6.4
    - multidict==5.1.0
    - murmurhash==1.0.5
    - nbconvert==5.6.1
    - nbformat==5.0.8
    - ndg-httpsclient==0.5.1
    - networkx==2.5
    - nimbusml==1.8.0
    - notebook==6.1.6
    - numexpr==2.7.2
    - numpy==1.18.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - onnx==1.7.0
    - onnxconverter-common==1.6.0
    - onnxmltools==1.4.1
    - onnxruntime==1.3.0
    - opencensus==0.7.11
    - opencensus-context==0.1.2
    - opencv-python==4.5.1.48
    - opencv-python-headless==4.3.0.36
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandas-ml==0.6.1
    - pandocfilters==1.4.3
    - papermill==1.2.1
    - paramiko==2.7.2
    - parso==0.8.1
    - pathspec==0.8.1
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.2.1
    - pkginfo==1.6.1
    - plac==0.9.6
    - pluggy==0.13.1
    - pmdarima==1.1.1
    - portalocker==1.7.1
    - preshed==2.0.1
    - prometheus-client==0.9.0
    - prometheus-flask-exporter==0.18.1
    - prompt-toolkit==3.0.10
    - protobuf==3.14.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py-cpuinfo==5.0.0
    - py-spy==0.3.3
    - py4j==0.10.9
    - pyarrow==1.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.0
    - pycodestyle==2.6.0
    - pydocstyle==5.1.1
    - pyflakes==2.2.0
    - pyglet==1.5.0
    - pygments==2.7.4
    - pyjwt==1.7.1
    - pylint==2.6.0
    - pynacl==1.4.0
    - pynvml==8.0.4
    - pyopenssl==19.1.0
    - pyrsistent==0.17.3
    - pyspark==3.0.1
    - python-editor==1.0.4
    - python-jsonrpc-server==0.4.0
    - python-language-server==0.35.0
    - pytorch-transformers==1.0.0
    - pytz==2020.5
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - pyzmq==20.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - quantlib==1.20
    - querystring-parser==1.2.4
    - ray==1.1.0
    - redis==3.5.3
    - regex==2020.11.13
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rope==0.18.0
    - rsa==4.7
    - ruamel-yaml==0.16.12
    - ruamel-yaml-clib==0.2.2
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-image==0.17.2
    - scikit-learn==0.22.2.post1
    - scp==0.13.3
    - scrapbook==0.5.0
    - secretstorage==3.3.0
    - send2trash==1.5.0
    - sentencepiece==0.1.95
    - shap==0.34.0
    - simpervisor==0.4
    - skl2onnx==1.4.9
    - sklearn==0.0
    - sklearn-pandas==1.7.0
    - smart-open==1.9.0
    - smmap==3.0.4
    - snowballstemmer==2.0.0
    - soupsieve==2.1
    - spacy==2.1.8
    - sqlalchemy==1.3.22
    - sqlparse==0.4.1
    - srsly==1.0.5
    - sshtunnel==0.1.5
    - statsmodels==0.10.2
    - tabulate==0.8.7
    - tenacity==6.3.1
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.1.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - textwrap3==0.9.2
    - thinc==7.0.8
    - tifffile==2020.9.3
    - tokenizers==0.9.4
    - toml==0.10.2
    - tornado==6.1
    - tqdm==4.55.1
    - traitlets==4.3.3
    - transformers==4.1.1
    - typed-ast==1.4.2
    - typing-extensions==3.7.4.3
    - ujson==4.0.1
    - urllib3==1.25.11
    - vsts==0.1.25
    - vsts-cd-manager==1.0.2
    - waitress==1.4.4
    - wasabi==0.8.0
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - websockets==8.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xgboost==0.90
    - xmltodict==0.12.0
    - yapf==0.30.0
    - yarl==1.6.3
    - zipp==3.4.0
    - zope-event==4.5.0
    - zope-interface==5.2.0
prefix: /anaconda/envs/azureml_py36
