$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: kvdep
endpoint_name: <ENDPOINT_NAME>
model:
  path: "."
code_configuration:
  code: code
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference:latest
  conda_file: env.yml
environment_variables:
  KV_SECRET_MULTIPLIER: multiplier@https://<KV_NAME>.vault.azure.net
instance_type: Standard_DS3_v2
instance_count: 1