name: run-notebooks

on: [push, pull_request]

env:
  ml-ws: default
  ml-rg: cody-azureml-examples
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook: [notebooks/sklearn/train-diabetes-ridge.ipynb,
                   notebooks/xgboost/train-iris.ipynb, 
                   notebooks/lightgbm/train-iris.ipynb, 
                   notebooks/pytorch/train-mnist-cnn.ipynb, 
                   notebooks/pytorch/train-deploy-mnist-mlproject.ipynb, 
                   notebooks/tensorflow-v2/train-iris-nn.ipynb,
                   notebooks/tensorflow-v2/train-mnist-nn.ipynb,
                   notebooks/fastai/train-pets-resnet34.ipynb,
                   notebooks/fastai/train-mnist-resnet18.ipynb]
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml
    - name: attach to workspace
      run: az ml folder attach -w ${{env.ml-ws}} -g ${{env.ml-rg}}
    - name: run notebook
      run: papermill ${{matrix.notebook}} out.ipynb -k python
#    - name: upload notebook artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{job.id}}
#        path: out.ipynb
