name: cleanup
on:
  schedule:
    - cron: "0 8 * * *"
  pull_request:
    branches:
      - main
    paths: 
      - .github/workflows/cleanup.yml
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: downgrade pip
      run: pip install pip==21.1.1
    - name: pip install
      run: pip install -r requirements.txt
      working-directory: python-sdk
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml -y
    - name: attach to workspace
      run: az ml folder attach -w main-python-sdk -g azureml-examples-rg
    - name: run cleanup script
      run: python cleanup.py
      working-directory: python-sdk
      continue-on-error: true
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: attach to workspace
      run: az ml folder attach -w main -g azureml-examples-rg
    - name: run cleanup script
      run: python cleanup.py
      working-directory: python-sdk
      continue-on-error: true
