name: cli-assets-data-iris-url
on:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - cli-preview
    paths:
      - cli/assets/data/iris-url.yml
      - .github/workflows/cli-assets-data-iris-url.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CLI_CREDS}}
    - name: install new ml cli
      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.71-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - name: setup workspace
      run: bash setup.sh
      working-directory: cli
    - name: create asset
      run: az ml data create -f assets/data/iris-url.yml
      working-directory: cli
