name: cli-jobs-train-lightgbm-iris-job
on:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - cli-preview
      - releases/current
    paths:
      - cli/jobs/train/lightgbm/iris/**
      - .github/workflows/cli-jobs-train-lightgbm-iris-job.yml
      - cli/setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_V2_CREDS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create job
      run: |
        echo "Creating job..."
        run_id=$(az ml job create -f jobs/train/lightgbm/iris/job.yml --query name -o tsv)
        echo "Streaming job..."
        az ml job stream -n $run_id >> log.txt
        echo "Getting job status..."
        sleep 1
        status=$(az ml job show -n $run_id --query status -o tsv)
        echo $status
        echo "Checking job status..."
        if [[ $status == "Completed" ]]
        then
          echo "Job completed"
        elif [[ $status ==  "Failed" ]]
        then
          echo "Job failed"
          exit 1
        else 
          echo "Job status not failed or completed"
          exit 2
        fi
      working-directory: cli
