name: cli-docs-how-to-deploy-declarative-safe-rollout-online-endpoints
on:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - cli-preview
    paths:
      - cli/how-to-deploy-declarative-safe-rollout-online-endpoints.sh
      - .github/workflows/cli-docs-how-to-deploy-declarative-safe-rollout-online-endpoints.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CLI_CREDS}}
    - name: install ml cli
      run: az extension add -n ml -y
    - name: setup workspace
      run: bash setup.sh
      working-directory: cli
    - name: docs installs
      run: sudo apt-get upgrade -y && sudo apt-get install uuid-runtime jq -y
    - name: test doc script
      run: set -e; bash -x how-to-deploy-declarative-safe-rollout-online-endpoints.sh
      working-directory: cli
      env:
        AZURE_STORAGE_KEY: ${ secrets.AzureStorageKey }
