name: cli-assets-data-iris-csv-example
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - cli/assets/data/iris-csv-example.yml
      - infra/**
      - .github/workflows/cli-assets-data-iris-csv-example.yml
      - cli/setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZUREML_CREDENTIALS}}
    - name: bootstrap resources
      run: bash bootstrap.sh
      working-directory: infra
      continue-on-error: false
    - name: setup
      run: |
          source "${{ github.workspace }}/infra/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/init_environment.sh";
          bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create asset
      run: |
          source "${{ github.workspace }}/infra/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/init_environment.sh";
          az ml data create -f assets/data/iris-csv-example.yml
      working-directory: cli
