name: cli-jobs-pipelines-with-components-basics-5a_env_public_docker_image-pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/8 * * *"
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - cli/jobs/pipelines-with-components/basics/5a_env_public_docker_image/**
      - infra/**
      - .github/workflows/cli-jobs-pipelines-with-components-basics-5a_env_public_docker_image-pipeline.yml
      - cli/run-pipeline-jobs.sh
      - cli/setup.sh
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZUREML_CREDENTIALS}}
    - name: bootstrap resources
      run: |
          echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}';
          bash bootstrap.sh
      working-directory: infra
      continue-on-error: false
    - name: setup-cli
      run: |
          source "${{ github.workspace }}/infra/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/init_environment.sh";
          bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run job
      run: |
          source "${{ github.workspace }}/infra/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/init_environment.sh";
          bash -x ../../../../run-job.sh pipeline.yml
      working-directory: cli/jobs/pipelines-with-components/basics/5a_env_public_docker_image
