name: cli-docs-how-to-train-autorest
on:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
      - cli-preview
    paths:
      - cli/how-to-train-autorest.py
      - .github/workflows/cli-docs-how-to-train-autorest.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CLI_CREDS}}
    - name: install new ml cli
      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.64-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - name: setup workspace
      run: bash setup.sh
      working-directory: cli
    - name: docs installs
      run: |
        pip install keyring artifacts-keyring
        pip install azure-mgmt-machinelearningservices==0.1.0.36102190 azure-cli-core --extra-index-url=https://pkgs.dev.azure.com/msdata/Vienna/_packaging/AzureML_ManagementFrontEnd/pypi/simple/ -U
    - name: test doc script
      run: python how-to-train-autorest.py
      working-directory: cli
