name: cli-scripts-deploy-safe-rollout-k8s-online-endpoints
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches:
      - main
    paths:
      - cli/deploy-safe-rollout-k8s-online-endpoints.sh
      - .github/workflows/cli-scripts-deploy-safe-rollout-k8s-online-endpoints.yml
      - cli/setup.sh
      - .github/amlarc-tool.sh
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_VAULT_NAME: amlarcgithubworkflowkv
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: scripts installs
      run: sudo apt-get upgrade -y && sudo apt-get install uuid-runtime jq -y
    - name: test script script
      run: set -e; bash -x deploy-safe-rollout-k8s-online-endpoints.sh
      working-directory: cli
    - name: file IcM when fails
      if: ${{ failure() }}
      run: |
        # download certificates
        export ICM_HOST_NAME=ICM-HOST-AML-EXAMPLES
        export ICM_CONNECTOR_ID_NAME=ICM-CONNECTOR-ID-AML-EXAMPLES
        export ICM_ROUTING_ID_NAME=ICM-ROUTING-ID-AML-EXAMPLES
        set -e; bash -x .github/amlarc-tool.sh download_icm_cert
        export ICM_HOST=$(cat icm_host)
        export CONNECTOR_ID=$(cat icm_connector_id)
        export ROUTING_ID=$(cat icm_routing_id)
        export SUMMARY=$(set -e; bash -x .github/amlarc-tool.sh gen_summary_for_github_test)
        set -e; bash -x .github/amlarc-tool.sh file_icm
      timeout-minutes: 30
