name: notebooks-cloud-data
on:
  schedule:
    - cron: "0 */8 * * *"
  pull_request:
    branches:
      - main
    paths:
      - v1/notebooks/cloud-data/**
      - .github/workflows/notebooks-cloud-data.yml
      - v1/notebooks/dev-requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook: ['blob-adls-numpy.ipynb', 'blob-adls-pandas.ipynb']
    steps:
    - name: check out repo
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: Run Install packages
      run: |
         chmod +x ./v1/scripts/install-packages.sh
         ./v1/scripts/install-packages.sh
      shell: bash
    - name: pip install notebook reqs
      run: pip install -r v1/notebooks/dev-requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: Run update-azure-extensions
      run: |
         chmod +x ./v1/scripts/update-azure-extensions.sh
         ./v1/scripts/update-azure-extensions.sh
      shell: bash
    - name: attach to workspace
      run: az ml folder attach -w main-python-sdk -g azureml-examples
    - name: run ${{matrix.notebook}}
      run: papermill ${{matrix.notebook}} - -k python
      working-directory: v1/notebooks/cloud-data
