name: python-sdk-tutorial-train-on-low-priority-aml-compute
on:
  schedule:
    - cron: "0 */24 * * *"
  pull_request:
    branches:
      - main
    paths:
      - v1/python-sdk/tutorials/train-on-low-priority-aml-compute/**
      - .github/workflows/python-sdk-tutorial-train-on-low-priority-aml-compute.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.7"
    - name: Run Install packages
      run: |
         chmod +x ./v1/scripts/install-packages.sh
         ./v1/scripts/install-packages.sh
      shell: bash
    - name: pip install
      run: pip install -r v1/python-sdk/requirements.txt
    - name: set up the IPython kernel
      run: |
        python -m ipykernel install --user --name azure_automl --display-name "Python (azure_automl)"
        pip list
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: Run update-azure-extensions
      run: |
         chmod +x ./v1/scripts/update-azure-extensions.sh
         ./v1/scripts/update-azure-extensions.sh
      shell: bash
    - name: attach to workspace
      run: az ml folder attach -w main-python-sdk -g azureml-examples-rg
    - name: run train-on-low-priority-aml-compute
      run: papermill -k python train-on-low-priority-aml-compute.ipynb train-on-low-priority-aml-compute.output.ipynb
      working-directory: v1/python-sdk/tutorials/train-on-low-priority-aml-compute
    - name: upload notebook's working folder as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: train-on-low-priority-aml-compute
        path: v1/python-sdk/tutorials/train-on-low-priority-aml-compute
