name: python-sdk-tutorial-using-rapids
on:
  schedule:
    - cron: "0 */8 * * *"
  pull_request:
    branches:
      - main
    paths:
      - v1/python-sdk/tutorials/using-rapids/**
      - .github/workflows/python-sdk-tutorial-using-rapids.yml
      - v1/python-sdk/requirements.txt
jobs:
  build:
    runs-on: ${{vars.V1_UBUNTU_RUNNER}}
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: install snappy
      run: sudo apt-get install libsnappy-dev
    - name: pip install
      run: pip install -r v1/python-sdk/requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml -y
    - name: attach to workspace
      run: az ml folder attach -w main -g azureml-examples
    - name: run 1.train-and-hpo.ipynb
      run: papermill 1.train-and-hpo.ipynb - -k python
      working-directory: v1/python-sdk/tutorials/using-rapids
    - name: run 2.train-multi-gpu.ipynb
      run: papermill 2.train-multi-gpu.ipynb - -k python
      working-directory: v1/python-sdk/tutorials/using-rapids
