name: run-tutorial-uk
on:
  pull_request:
    branches:
      - main
    paths:
      - tutorials/using-k8sedge/**
  schedule:
    - cron: "0 9 * * *"
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
    - name: check code format
      run: black --check .
    - name: check notebook format
      run: black-nb --clear-output --check .
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run production-deploy-to-k8s-gpu.ipynb
      run: papermill tutorials/using-k8sedge/production-deploy-to-k8s-gpu.ipynb - -k python