name: run-tutorial-upl
on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - tutorials/using-pytorch-lightning/**
      - environments/pt-lightning.yml
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run 1.train-single-node.ipynb
      run: papermill tutorials/using-pytorch-lightning/1.train-single-node.ipynb - -k python
    - name: run 2.log-with-tensorboard.ipynb
      run: papermill tutorials/using-pytorch-lightning/2.log-with-tensorboard.ipynb - -k python
    - name: run 3.log-with-mlflow.ipynb
      run: papermill tutorials/using-pytorch-lightning/3.log-with-mlflow.ipynb - -k python
    - name: run 4.train-multi-node-ddp.ipynb
      run: papermill tutorials/using-pytorch-lightning/4.train-multi-node-ddp.ipynb - -k python
