name: run-tutorial-ur
on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - tutorials/using-rapids/**
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: install snappy
      run: sudo apt-get install libsnappy-dev
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run 1.train-and-hpo.ipynb
      run: papermill tutorials/using-rapids/1.train-and-hpo.ipynb - -k python
    - name: run 2.train-multi-gpu.ipynb
      run: papermill tutorials/using-rapids/2.train-multi-gpu.ipynb - -k python
