name: run-tutorial-mwm
on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - tutorials/music-with-ml/**
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: install requirements
      run: sudo apt-get update -qq && sudo apt-get install -qq libfluidsynth1 fluid-soundfont-gm build-essential libasound2-dev libjack-dev
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run 1.intro-to-magenta.ipynb
      run: papermill tutorials/music-with-ml/1.intro-to-magenta.ipynb - -k python
