name: run-examples
on:
  push: 
    branches:
      - main
    paths:
      - "examples/**"
      - "code/**"
      - "environments/**"
      - "mlprojects/**"
      - "data/**"
  pull_request:
    branches:
      - main
    paths:
      - "examples/**"
      - "code/**"
      - "environments/**"
      - "mlprojects/**"
      - "data/raw/**"
  schedule:
      - cron: "0 0/2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        example: ['examples/deploy/pytorch-mnist-aks-cpu.py', 'examples/deploy/sklearn-diabetes-aks-cpu.py', 'examples/train/deepspeed-cifar.py', 'examples/train/fastai-mnist-mlproject.py', 'examples/train/fastai-mnist.py', 'examples/train/fastai-pets.py', 'examples/train/lightgbm-iris.py', 'examples/train/pytorch-mnist-mlproject.py', 'examples/train/pytorch-mnist.py', 'examples/train/sklearn-diabetes-mlproject.py', 'examples/train/sklearn-diabetes.py', 'examples/train/tensorflow-iris.py', 'examples/train/tensorflow-mnist-distributed-horovod.py', 'examples/train/tensorflow-mnist-distributed.py', 'examples/train/tensorflow-mnist.py', 'examples/train/xgboost-iris.py']
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run example
      run: python ${{matrix.example}}
