name: sdk-jobs-pipelines-stepsequence-pipeline_with_step_sequence_dummy_dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
  pull_request:
    branches:
      - main
    paths:
      - sdk/python/jobs/pipelines/stepsequence/pipeline_with_step_sequence_dummy_dependencies.ipynb
      - .github/workflows/sdk-jobs-pipelines-stepsequence-pipeline_with_step_sequence_dummy_dependencies.yml
      - "!sdk/python/jobs/pipelines/stepsequence/**/*.md"
      - sdk/python/dev-requirements.txt
      - infra/bootstrapping/**
      - sdk/python/setup.sh

permissions:
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: pip install notebook reqs
      run: pip install -r sdk/python/dev-requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.OIDC_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.OIDC_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.OIDC_AZURE_SUBSCRIPTION_ID }}
    - name: bootstrap resources
      run: |
          echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}';
          bash bootstrap.sh
      working-directory: infra/bootstrapping
      continue-on-error: false
    - name: setup SDK
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          bash setup.sh
      working-directory: sdk/python
      continue-on-error: true
    - name: setup-cli
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: Eagerly cache access tokens for required scopes
      run: |
          # Workaround for azure-cli's lack of support for ID token refresh
          # Taken from: https://github.com/Azure/login/issues/372#issuecomment-2056289617

          # Management
          az account get-access-token --scope https://management.azure.com/.default --output none
          # ML
          az account get-access-token --scope https://ml.azure.com/.default --output none
    - name: install ml extension
      run: az extension add -n ml -y
    - name: run jobs/pipelines/stepsequence/pipeline_with_step_sequence_dummy_dependencies.ipynb
      run: |
          source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
          source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
          bash "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh" generate_workspace_config "../../.azureml/config.json";
          bash "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh" replace_template_values "pipeline_with_step_sequence_dummy_dependencies.ipynb";
          [ -f "../../.azureml/config" ] && cat "../../.azureml/config";
          papermill -k python pipeline_with_step_sequence_dummy_dependencies.ipynb pipeline_with_step_sequence_dummy_dependencies.output.ipynb
      working-directory: sdk/python/jobs/pipelines/stepsequence
    - name: upload notebook's working folder as an artifact
      if: ${{ always() }}
      uses: ./.github/actions/upload-artifact
      with:
        name: stepsequence
        path: sdk/python/jobs/pipelines/stepsequence
