name: sdk-jobs-pipelines-basic_pipeline-basic_pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
  pull_request:
    branches:
      - sdk-preview
      - april-sdk-preview
    paths:
      - sdk/**
      - .github/workflows/sdk-jobs-pipelines-basic_pipeline-basic_pipeline.yml
      - notebooks/dev-requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
      with:
        ref: april-sdk-preview
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: pip install notebook reqs
      run: pip install -r notebooks/dev-requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: setup SDK
      run: bash setup.sh
      working-directory: sdk
      continue-on-error: true
    - name: setup CLI
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run jobs/pipelines/basic_pipeline/basic_pipeline.ipynb
      run: |
          sed -i -e "s/<SUBSCRIPTION_ID>/6560575d-fa06-4e7d-95fb-f962e74efd7a/g" basic_pipeline.ipynb
          sed -i -e "s/<RESOURCE_GROUP>/azureml-examples-rg/g" basic_pipeline.ipynb
          sed -i -e "s/<AML_WORKSPACE_NAME>/main/g" basic_pipeline.ipynb
          sed -i -e "s/InteractiveBrowserCredential/AzureCliCredential/g" basic_pipeline.ipynb

          papermill -k python basic_pipeline.ipynb basic_pipeline.output.ipynb
      working-directory: sdk/jobs/pipelines/basic_pipeline
    - name: upload notebook's working folder as an artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: basic_pipeline
        path: sdk/jobs/pipelines/basic_pipeline
