name: sdk-jobs-pipelines-nyc-taxi-nyc-taxi
on:
  workflow_dispatch:
  pull_request:
    branches:
      - sdk-preview
      - march-sdk-preview
    paths:
      - sdk/**
      - .github/workflows/sdk-jobs-pipelines-nyc-taxi-nyc-taxi.yml
      - notebooks/dev-requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
      with:
        ref: march-sdk-preview    
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: pip install notebook reqs
      run: pip install -r notebooks/dev-requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: setup SDK
      run: bash setup.sh
      working-directory: sdk
      continue-on-error: true
    - name: setup CLI
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run jobs/pipelines/nyc-taxi/nyc-taxi.ipynb
      run: |
          sed -i -e "s/<SUBSCRIPTION_ID>/6560575d-fa06-4e7d-95fb-f962e74efd7a/g" nyc-taxi.ipynb
          sed -i -e "s/<RESOURCE_GROUP>/azureml-examples-rg/g" nyc-taxi.ipynb
          sed -i -e "s/<AML_WORKSPACE_NAME>/main/g" nyc-taxi.ipynb
          sed -i -e "s/InteractiveBrowserCredential/AzureCliCredential/g" nyc-taxi.ipynb
          
          papermill nyc-taxi.ipynb - -k python
      working-directory: sdk/jobs/pipelines/nyc-taxi
