name: sdk-jobs-single-step-pytorch-iris-pytorch-iris
on:
  schedule:
    - cron: "0 */8 * * *"
  pull_request:
    branches:
      - sdk-preview
    paths:
      - sdk/**
      - .github/workflows/sdk-jobs-single-step-pytorch-iris-pytorch-iris.yml
      - notebooks/dev-requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: pip install notebook reqs
      run: pip install -r notebooks/dev-requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: setup SDK
      run: bash setup.sh
      working-directory: sdk
      continue-on-error: true
    - name: setup CLI
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run jobs/single-step/pytorch/iris/pytorch-iris.ipynb
      run: |
          sed -i -e "s/<SUBSCRIPTION_ID>/6560575d-fa06-4e7d-95fb-f962e74efd7a/g" pytorch-iris.ipynb
          sed -i -e "s/<RESOURCE_GROUP>/azureml-examples-rg/g" pytorch-iris.ipynb
          sed -i -e "s/<AML_WORKSPACE_NAME>/main/g" pytorch-iris.ipynb
          sed -i -e "s/InteractiveBrowserCredential/AzureCliCredential/g" pytorch-iris.ipynb

          # generate a random workspace name
          sed -i -e "s/mlw-basic-prod/mlw-basic-prod-$(echo $RANDOM | md5sum | head -c 10)/g" pytorch-iris.ipynb

          # skip other workpace creation commands for now
          sed -i -e "s/ml_client.begin_create_or_update(ws_with_existing)/# ml_client.begin_create_or_update(ws_with_existing)/g" pytorch-iris.ipynb        
          sed -i -e "s/ml_client.workspaces.begin_create(ws_private_link)/# ml_client.workspaces.begin_create(ws_private_link)/g" pytorch-iris.ipynb        
          sed -i -e "s/ml_client.workspaces.begin_create(ws_private_link)/# ws_from_config = MLClient.from_config()/g" pytorch-iris.ipynb            
          
          papermill pytorch-iris.ipynb - -k python
      working-directory: sdk/jobs/single-step/pytorch/iris
