name: tutorial-deploy-triton
on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - experimental/deploy-triton/**
      - .github/workflows/tutorial-deploy-triton.yml
      - requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run 1.densenet-local.ipynb
      run: papermill 1.densenet-local.ipynb - -k python
      working-directory: experimental/deploy-triton
    - name: run 2.bidaf-aks-v100.ipynb
      run: papermill 2.bidaf-aks-v100.ipynb - -k python
      working-directory: experimental/deploy-triton
