name: tutorial-using-cli
on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - experimental/using-cli/**
      - .github/workflows/tutorial-using-cli.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        workflow: [hello-world, manage-assets, lightgbm-iris, lightgbm-iris-sweep, pytorch-cifar-distributed, batch-score]
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install the new ml extension
      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.64-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - name: run setup
      run: bash setup.sh
      working-directory: experimental/using-cli
    - name: run workflow
      run: bash ${{matrix.workflow}}.sh #> ./logs.txt
      working-directory: experimental/using-cli
#    - name: upload logs 
#      if: always()
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{matrix.workflow}}
#        path: ./experimental/using-cli/logs.txt
