name: tutorial-an-introduction
on:
  schedule:
    - cron: "0 0/1 * * *"
  pull_request:
    branches:
      - main
    paths:
      - tutorials/an-introduction/**
      - .github/workflows/tutorial-an-introduction.yml
      - requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run 1.hello-world.ipynb
      run: papermill 1.hello-world.ipynb - -k python
      working-directory: tutorials/an-introduction
    - name: run 2.pytorch-model.ipynb
      run: papermill 2.pytorch-model.ipynb - -k python
      working-directory: tutorials/an-introduction
    - name: run 3.pytorch-model-cloud-data.ipynb
      run: papermill 3.pytorch-model-cloud-data.ipynb - -k python
      working-directory: tutorials/an-introduction